### PR TITLE
implemented onItemPage added scrapeItemPageHTML

### PR DESCRIPTION
**Pull request by LeopoldoMoreno**
Bigger PR, implemented the on item page scraping, at the moment this is only for Thumbnails, but would theoretically work for metadata too with a bit of work. Atm only implemented on plainHTML scrape and ddlbase specific scraper. Also corrected all instances of "onItemPage" keys being strings into bools.  

This does make more HTML requests so it is slower on processing some so not 100% sure if we want to do metadata this way be default.

### CODE REVIEW

**Comment by FrenchGithubUser** [comment]
seems like a good idea. however, did you make sure that for the sites that have the thumbnail on item page, the thumbnail url can't be guessed from the item name ? (something like https://site-name.com/thumb/game-name.jpg).

**Comment by LeopoldoMoreno** [comment]
So none of the sources we have currently implemented, would that be possible. If we wanted to create the option in the future to prevent unnecessary requests, that would likely require a schema change. Update the JSON to include a "guessableThumbnail" bool or something.

**Comment by FrenchGithubUser** [comment]
I'm not sure to fully understand what you mean.

But what is sure is that unnecessary requests should be avoided from the beginning.

Are you sure that the sources you implemented this `onItemPage` attribute absolutely need it ?

**Comment by LeopoldoMoreno** [comment]
All I was saying is that method you suggested does not work for any of the sources that are currently supported. 

If you wanted to implement something like that in the future to limit calls it would require a new book in the json files to indicate it as such.

They don't absolutely need it if all you care about is the items being returned in the initial search, but if you want to have a standardized experience with images then yes it is for some sources. 

If this isnt the solution you want to go with to implement onItemPage that is fine, but I do not know of a way to get that information without making additional requests.

**Comment by FrenchGithubUser** [comment]
Okay I see, then I will merge.

However, we could implement an option in the settings to disable image loading, for people who would use hatt in an automated pipeline and wouldn't need such an amount of data

**Pull request merged**
