### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by LeopoldoMoreno**
So this is a pretty big rewrite of the current index.js but most notable site descriptions. I alphabetized the list, and had chatGPT generate the descriptions for the sites if they didn't already have one provided. I didn't spot any inaccuracies when I reviewed it.

### CODE REVIEW

**Comment by FrenchGithubUser** [comment]
pretty neat, wanted to do that for a while, nice you did it

**Comment by FrenchGithubUser** [comment]
maybe this list could be used to update the readme for the supported sites, I think that a few of them are missing

**Comment by LeopoldoMoreno** [comment]
> maybe this list could be used to update the readme for the supported sites, I think that a few of them are missing

The biggest issue I see with this update was based on all source json files, and some of them don't work due to various reasons such as cookie/js issues or cloudflare blocking. Not sure if we want to list all of them if not all of them work.

**Comment by FrenchGithubUser** [comment]
I see, indeed, once some automated tests are made, it will be usable

**Pull request merged**
